// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package stan

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	domain "social/internal/domain"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeSocialInternalTransportStan(in *jlexer.Lexer, out *NewsPersistRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "owner_id":
			out.OwnerID = string(in.String())
		case "news":
			if in.IsNull() {
				in.Skip()
				out.News = nil
			} else {
				in.Delim('[')
				if out.News == nil {
					if !in.IsDelim(']') {
						out.News = make([]*domain.News, 0, 8)
					} else {
						out.News = []*domain.News{}
					}
				} else {
					out.News = (out.News)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *domain.News
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(domain.News)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.News = append(out.News, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeSocialInternalTransportStan(out *jwriter.Writer, in NewsPersistRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.OwnerID))
	}
	{
		const prefix string = ",\"news\":"
		out.RawString(prefix)
		if in.News == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.News {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NewsPersistRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeSocialInternalTransportStan(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NewsPersistRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeSocialInternalTransportStan(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NewsPersistRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeSocialInternalTransportStan(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NewsPersistRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeSocialInternalTransportStan(l, v)
}
func easyjson3c9d2b01DecodeSocialInternalTransportStan1(in *jlexer.Lexer, out *FriendsActionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Action":
			out.Action = string(in.String())
		case "UserID":
			out.UserID = string(in.String())
		case "FriendsID":
			if in.IsNull() {
				in.Skip()
				out.FriendsID = nil
			} else {
				in.Delim('[')
				if out.FriendsID == nil {
					if !in.IsDelim(']') {
						out.FriendsID = make([]string, 0, 4)
					} else {
						out.FriendsID = []string{}
					}
				} else {
					out.FriendsID = (out.FriendsID)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.FriendsID = append(out.FriendsID, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeSocialInternalTransportStan1(out *jwriter.Writer, in FriendsActionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Action\":"
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"FriendsID\":"
		out.RawString(prefix)
		if in.FriendsID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.FriendsID {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FriendsActionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeSocialInternalTransportStan1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FriendsActionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeSocialInternalTransportStan1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FriendsActionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeSocialInternalTransportStan1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FriendsActionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeSocialInternalTransportStan1(l, v)
}
