global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'messenger-otus-server'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'messenger-otus'
    static_configs:
      - targets: ['messenger-otus:10003']
        labels:
          dc: "dc1"
          hostname: "messenger-otus-server-1"
          service: "messenger-otus"