addr: ":10003"

auth:
  addr: "localhost:10001"

ch:
  dsn: "tcp://127.0.0.1:9000?debug=false&database=default&username=default&password=password"
  push_timeout: "1s"

sharding:
  count_nodes: 2

logger:
  level: "info"