http_addr: ":10003"
grpc_addr: ":10004"

auth:
  addr: "localhost:10001"

ch:
  dsn: "tcp://127.0.0.1:9000?debug=false&database=default&username=default&password=password"
  push_timeout: "1s"

sharding:
  count_nodes: 2

jaeger:
  agent_addr: "0.0.0.0:6831"
  service_name: "messenger"

consul:
  addr: "localhost:8500"
  agent_addr: "127.0.0.1:10003"
  service_id: "messenger-service"
  service_name: "messenger"

zabbix:
  host: "localhost"
  port: 10051

logger:
  level: "info"