http_addr: ":10003"
grpc_addr: ":10004"

auth:
  addr: "localhost:10001"

ch:
  dsn: "tcp://127.0.0.1:9000?debug=false&database=default&username=default&password=password"
  push_timeout: "1s"

sharding:
  count_nodes: 2

jaeger:
  agent_addr: "0.0.0.0:6831"
  service_name: "social"

logger:
  level: "info"