// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package stan

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan(in *jlexer.Lexer, out *NewsActionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan(out *jwriter.Writer, in NewsActionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NewsActionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NewsActionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NewsActionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NewsActionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan(l, v)
}
func easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan1(in *jlexer.Lexer, out *FriendsActionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Action":
			out.Action = string(in.String())
		case "UserID":
			out.UserID = string(in.String())
		case "FriendsID":
			if in.IsNull() {
				in.Skip()
				out.FriendsID = nil
			} else {
				in.Delim('[')
				if out.FriendsID == nil {
					if !in.IsDelim(']') {
						out.FriendsID = make([]string, 0, 4)
					} else {
						out.FriendsID = []string{}
					}
				} else {
					out.FriendsID = (out.FriendsID)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.FriendsID = append(out.FriendsID, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan1(out *jwriter.Writer, in FriendsActionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Action\":"
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"FriendsID\":"
		out.RawString(prefix)
		if in.FriendsID == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.FriendsID {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FriendsActionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FriendsActionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeSocialNetworkInternalTransportStan1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FriendsActionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FriendsActionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeSocialNetworkInternalTransportStan1(l, v)
}
