version: '3.7'

services:
  auth-storage:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:stage
    container_name: auth-storage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: auth
    volumes:
      - auth-storage-data:/var/lib/mysql
    networks:
      - otus-highload-network

  social-storage:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:stage
    container_name: social-storage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    volumes:
      - social-storage-data:/var/lib/mysql
    networks:
      - otus-highload-network

  cache:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cache
    image: redis:stage
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data
    networks:
      - otus-highload-network

  nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--cluster_id=stan-cluster"
      - "--store=file"
      - "--dir=datastore"
      - "--http_port=8222"
      - "--max_age=1h"
      - "--max_inactivity=1h"
    networks:
      - otus-highload-network

  auth-migrator:
    build:
      context: ../tools/migrator
      dockerfile: Dockerfile
    image: migrator:mysql
    container_name: auth-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(auth-storage:3306)/auth"
      OPERATION: "up"
    volumes:
      - ../backend/migrations/mysql/auth:/app/migrations
    depends_on:
      - auth-storage
    networks:
      - otus-highload-network

  social-migrator:
    build:
      context: ../tools/migrator
      dockerfile: Dockerfile
    image: migrator:mysql
    container_name: social-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(social-storage:3306)/social-network"
      OPERATION: "up"
    volumes:
      - ../backend/migrations/mysql/social:/app/migrations
    depends_on:
      - social-storage
    networks:
      - otus-highload-network

  ch-cluster:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-cluster
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch-cluster-data:/opt/clickhouse/data
      - ./clickhouse/cluster/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/cluster/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - ch-shard-0
      - ch-shard-1
    networks:
      - otus-highload-network

  ch-shard-0:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-0
    volumes:
      - ch-shard-0-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - otus-highload-network

  ch-shard-1:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-1
    volumes:
      - ch-shard-1-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - otus-highload-network

  ch-cluster-migrator:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-cluster-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-cluster:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ../backend/migrations/clickhouse/cluster:/app/migrations
    networks:
      - otus-highload-network
    depends_on:
      - ch-cluster

  ch-shard-migrator-0:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-0
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-0:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ../backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - otus-highload-network
    depends_on:
      - ch-shard-0

  ch-shard-migrator-1:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-1
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-1:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ../backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - otus-highload-network
    depends_on:
      - ch-shard-1

  auth:
    build:
      context: ../backend/auth
      dockerfile: Dockerfile
    image: auth:otus
    container_name: auth-otus
    environment:
      - ADDR=0.0.0.0:10001
      - STORAGE_DSN=user:password@tcp(auth-storage:3306)/auth?parseTime=true
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
      - LOGGER_LEVEL=info
    depends_on:
      - auth-storage
    networks:
      - otus-highload-network

  social:
    build:
      context: ../backend/social
      dockerfile: Dockerfile
    image: social:otus
    container_name: social-otus
    environment:
      - ADDR=0.0.0.0:10002
      - AUTH_ADDR=auth-otus:10001
      - STORAGE_DSN=user:password@tcp(social-storage:3306)/social-network?parseTime=true
      - HEATER_AUTH_DSN=user:password@tcp(auth-storage:3306)/auth?parseTime=true
      - HEATER_SOCIAL_DSN=user:password@tcp(social-storage:3306)/social-network?parseTime=true
      - STAN_CLUSTER_ID=stan-cluster
      - STAN_ADDR=nats://nats-streaming:4222
      - LOGGER_LEVEL=info
    depends_on:
      - social-storage
      - cache
      - nats-streaming
    networks:
      - otus-highload-network

  messenger:
    build:
      context: ../backend/messenger
      dockerfile: Dockerfile
    image: messenger:otus
    container_name: messenger-otus
    environment:
      - ADDR=0.0.0.0:10003
      - AUTH_ADDR=auth-otus:10001
      - CH_DSN=tcp://ch-cluster:9000?database=default&username=default&password=password
      - SHARDING_COUNT_NODES=2
    restart: unless-stopped
    networks:
      - otus-highload-network
    depends_on:
      - ch-cluster

  gateway:
    build:
      context: ../backend/gateway
      dockerfile: Dockerfile
    image: gateway:otus
    container_name: gateway-otus
    ports:
      - '10000:10000'
    environment:
      - ADDR=0.0.0.0:10000
      - AUTH_ADDR=auth-otus:10001
      - SOCIAL_ADDR=social-otus:10002
      - MESSENGER_ADDR=messenger-otus:10003
      - LOGGER_LEVEL=info
    depends_on:
      - auth
      - social
      - messenger
    networks:
      - otus-highload-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:stage
    container_name: frontend
    ports:
      - '8080:80'
    networks:
      - otus-highload-network

volumes:
  auth-storage-data:
  social-storage-data:
  ch-cluster-data:
  ch-shard-0-data:
  ch-shard-1-data:
  redis-cache-data:

networks:
  otus-highload-network:
    name: otus-highload-network
    driver: bridge