version: '3.7'

services:
  storage:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:stage
    container_name: mysql-storage
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    volumes:
      - mysql-storage-data:/var/lib/mysql
    networks:
      - stage-network

  cache:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cache
    image: redis:stage
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data
    networks:
      - stage-network

  nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--cluster_id=stan-cluster"
      - "--store=file"
      - "--dir=datastore"
      - "--http_port=8222"
      - "--max_age=1h"
      - "--max_inactivity=1h"
    networks:
      - stage-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - storage
    networks:
      - stage-network

  migrator:
    build:
      context: ../tools/migrator
      dockerfile: Dockerfile
    image: migrator:mysql
    container_name: mysql-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(mysql-storage:3306)/social-network"
      OPERATION: "up"
    volumes:
      - ../backend/migrations:/app/migrations
    depends_on:
      - storage
    networks:
      - stage-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend:stage
    container_name: backend
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(mysql-storage:3306)/social-network?parseTime=true
      - STAN_CLUSTER_ID=stan-cluster
      - STAN_ADDR=nats://nats-streaming:4222
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
    depends_on:
      - storage
      - cache
      - nats-streaming
    networks:
      - stage-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:stage
    container_name: frontend
    ports:
      - '8081:80'
    depends_on:
      - backend
    networks:
      - stage-network

volumes:
  mysql-storage-data:
  redis-cache-data:

networks:
  stage-network:
    name: stage-network
    driver: bridge