version: '3.7'

services:
  storage:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:stage
    container_name: mysql-storage
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    volumes:
      - mysql-storage-data:/var/lib/mysql
    networks:
      - otus-highload-network

  cache:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cache
    image: redis:stage
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data
    networks:
      - otus-highload-network

  nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--cluster_id=stan-cluster"
      - "--store=file"
      - "--dir=datastore"
      - "--http_port=8222"
      - "--max_age=1h"
      - "--max_inactivity=1h"
    networks:
      - otus-highload-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - storage
    networks:
      - otus-highload-network

  migrator:
    build:
      context: ../tools/migrator
      dockerfile: Dockerfile
    image: migrator:mysql
    container_name: mysql-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(mysql-storage:3306)/social-network"
      OPERATION: "up"
    volumes:
      - ../backend/migrations:/app/migrations
    depends_on:
      - storage
    networks:
      - otus-highload-network

  auth:
    build:
      context: ../backend/auth
      dockerfile: Dockerfile
    image: auth:otus
    container_name: auth-otus
    environment:
      - ADDR=0.0.0.0:10001
      - STORAGE_DSN=user:password@tcp(mysql-storage:3306)/social-network?parseTime=true
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
      - LOGGER_LEVEL=info
    depends_on:
      - storage
    networks:
      - otus-highload-network

  social:
    build:
      context: ../backend/social
      dockerfile: Dockerfile
    image: social:otus
    container_name: social-otus
    environment:
      - ADDR=0.0.0.0:10002
      - STORAGE_DSN=user:password@tcp(mysql-storage:3306)/social-network?parseTime=true
      - STAN_CLUSTER_ID=stan-cluster
      - STAN_ADDR=nats://nats-streaming:4222
      - LOGGER_LEVEL=info
    depends_on:
      - storage
      - cache
      - nats-streaming
    networks:
      - otus-highload-network

  gateway:
    build:
      context: ../backend/gateway
      dockerfile: Dockerfile
    image: gateway:otus
    container_name: gateway-otus
    ports:
      - '10000:10000'
    environment:
      - ADDR=0.0.0.0:10000
      - AUTH_ADDR=auth-otus:10001
      - SOCIAL_ADDR=social-otus:10002
      - MESSENGER_ADDR=messenger-otus:10003
      - LOGGER_LEVEL=info
    depends_on:
      - auth
      - social
    networks:
      - otus-highload-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:stage
    container_name: frontend
    ports:
      - '8081:80'
    depends_on:
      - gateway
    networks:
      - otus-highload-network

volumes:
  mysql-storage-data:
  redis-cache-data:

networks:
  otus-highload-network:
    name: otus-highload-network
    driver: bridge